In [1]:
import numpy as np

In [14]:
A = np.random.rand(3,2)
B = np.random.rand(3,2)
C = np.random.rand(2,1)
A

array([[0.7593518 , 0.2673707 ],
       [0.57656718, 0.26375659],
       [0.61419966, 0.08747376]])

In [1]:
import torch
from torch.autograd import grad
import torch.nn as nn

In [20]:
# Create some dummy data.
#x = torch.ones(2, 2, requires_grad=True)
x = torch.Tensor([[2.0,3.0],[1.0,5.0]]); x.requires_grad = True
gt = torch.ones_like(x) * 16 - 0.5  # "ground-truths" 

# We will use MSELoss as an example.
loss_fn = nn.MSELoss()

# Do some computations.
v = x + 2
y = v ** 2

# Compute loss.
loss = loss_fn(y, gt)

print(f'Loss: {loss}')

# Now compute gradients:
d_loss_dx = grad(outputs=loss, inputs=x)
print(f'dloss/dx:\n {d_loss_dx}')

Loss: 313.75
dloss/dx:
 (tensor([[  2.0000,  47.5000],
        [-19.5000, 234.5000]]),)


In [34]:
# Create some dummy data.
#x = torch.ones(2, 2, requires_grad=True)
x1 = torch.Tensor([[2.0,3.0],[1.0,5.0]]); x1.requires_grad = True
x2 = torch.Tensor([[1.0,4.0],[2.0,7.0]]); x2.requires_grad = True
gt = torch.ones_like(x1) * 16 - 0.5  # "ground-truths" 

# We will use MSELoss as an example.
loss_fn = nn.MSELoss()

# Do some computations.
y = x1 * x2

# Compute loss.
loss = loss_fn(y, gt)

print(f'Loss: {loss}')

# Now compute gradients:
d_loss_dx = grad(outputs=loss, inputs=[x1,x2])
print(f'dloss/dx:\n {d_loss_dx}')

Loss: 189.25
dloss/dx:
 (tensor([[ -6.7500,  -7.0000],
        [-13.5000,  68.2500]]), tensor([[-13.5000,  -5.2500],
        [ -6.7500,  48.7500]]))


In [22]:
y

tensor([[ 2., 12.],
        [ 2., 35.]], grad_fn=<MulBackward0>)

In [30]:
torch.mm(x1,x2)

tensor([[ 8., 29.],
        [11., 39.]], grad_fn=<MmBackward0>)

In [35]:
x1 @ x2

tensor([[ 8., 29.],
        [11., 39.]], grad_fn=<MmBackward0>)